num=input("경기장은 어디입니까? : ")
num1=input("이긴 팀은 어디입니까? : ")
num2=input("진 팀은 어디입니까? : ")
num3=input("우수선수는 누구입니까? : ")
num4=input("스코어는 몇대 몇 입니까? : ")

print("=" * 20)
print("오늘",num,"에서 야구 경기가 열렸습니다.")
print(num1,"과",num2,"은 치열한 공방전을 펼쳤습니다.")
print(num3,"이 맹활약을 하였습니다.")
print("결국",num1,"이(가)",num2,"을(를)", num4,"로 이겼습니다.")
print("=" * 20)